# Generated by Django 5.0.1 on 2024-01-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='user_password',
        ),
    ]
